export const FETCH_SUBSCRIPTION_START = 'FETCH_SUBSCRIPTION_START';
export const FETCH_SUBSCRIPTION_SUCCESS = 'FETCH_SUBSCRIPTION_SUCCESS';
export const FETCH_SUBSCRIPTION_ERROR = 'FETCH_SUBSCRIPTION_ERROR';

export const DELETE_NOTIFICATION_START = 'DELETE_NOTIFICATION_START';
export const DELETE_NOTIFICATION_SUCCESS = 'DELETE_NOTIFICATION_SUCCESS';
export const DELETE_NOTIFICATION_ERROR = 'DELETE_NOTIFICATION_ERROR';

export const FETCH_ALLNOTIFICATION_ERROR = 'FETCH_ALLNOTIFICATION_ERROR';
export const FETCH_ALLNOTIFICATION_START = 'FETCH_ALLNOTIFICATION_START';
export const FETCH_ALLNOTIFICATION_SUCCESS = 'FETCH_ALLNOTIFICATION_SUCCESS';

export const NOTIAPI_START = 'NOTIAPI_START';
export const NOTIAPI_SUCCESS = 'NOTIAPI_SUCCESS';
export const NOTIAPI_ERROR = 'NOTIAPI_ERROR';


export const GET_MEMBER_BY_MOBILE_START = 'GET_MEMBER_BY_MOBILE_START';
export const GET_MEMBER_BY_MOBILE_SUCCESS = 'GET_MEMBER_BY_MOBILE_SUCCESS';
export const GET_MEMBER_BY_MOBILE_ERROR = 'GET_MEMBER_BY_MOBILE_ERROR';

export const MEMBERSHIP_FOR_MEMBER_START = 'MEMBERSHIP_FOR_MEMBER_START';
export const MEMBERSHIP_FOR_MEMBER_SUCCESS = 'MEMBERSHIP_FOR_MEMBER_SUCCESS';
export const MEMBERSHIP_FOR_MEMBER_ERROR = 'MEMBERSHIP_FOR_MEMBER_ERROR';

export const GET_MY_GYM_START = 'GET_MY_GYM_START';
export const GET_MY_GYM_SUCCESS = 'GET_MY_GYM_SUCCESS';
export const GET_MY_GYM_ERROR = 'GET_MY_GYM_ERROR';

export const MEMBER_ALL_GYM_START = 'MEMBER_ALL_GYM_START';
export const MEMBER_ALL_GYM_SUCCESS = 'MEMBER_ALL_GYM_SUCCESS';
export const MEMBER_ALL_GYM_ERROR = 'MEMBER_ALL_GYM_ERROR';

export const SEND_NOTIFICATION_START = 'SEND_NOTIFICATION_START';
export const SEND_NOTIFICATION_SUCCESS = 'SEND_NOTIFICATION_SUCCESS';
export const SEND_NOTIFICATION_ERROR = 'SEND_NOTIFICATION_ERROR';

export const FACILITY_UPDATE_START = 'FACILITY_UPDATE_START';
export const FACILITY_UPDATE_SUCCESS = 'FACILITY_UPDATE_SUCCESS';
export const FACILITY_UPDATE_ERROR = 'FACILITY_UPDATE_ERROR';

export const UPADATESERVICES_START = 'UPADATESERVICES_START';
export const UPADATESERVICES_SUCCESS = 'UPADATESERVICES_SUCCESS';
export const UPADATESERVICES_ERROR = 'UPADATESERVICES_ERROR';

export const ABOUT_COMMENT_START = 'ABOUT_COMMENT_START';
export const ABOUT_COMMENT_SUCCESS = 'ABOUT_COMMENT_SUCCESS';
export const ABOUT_COMMENT_ERROR = 'ABOUT_COMMENT_ERROR';

export const RENEW_MESSAGE_START = 'RENEW_MESSAGE_START';
export const RENEW_MESSAGE_SUCCESS = 'RENEW_MESSAGE_SUCCESS';
export const RENEW_MESSAGE_ERROR = 'RENEW_MESSAGE_ERROR';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';


export const RENEWMEMBERSHIP_START = 'RENEWMEMBERSHIP_START';
export const RENEWMEMBERSHIP_SUCCESS = 'RENEWMEMBERSHIP_SUCCESS';
export const RENEWMEMBERSHIP_ERROR = 'RENEWMEMBERSHIP_ERROR';



export const LOGIN_BALANCESHEET_START = 'LOGIN_BALANCESHEET_START';
export const LOGIN_BALANCESHEET_SUCCESS = 'LOGIN_BALANCESHEET_SUCCESS';
export const LOGIN_BALANCESHEET_ERROR = 'LOGIN_BALANCESHEET_ERROR';


export const FORGETPIN_BALANCESHEET_START = 'FORGETPIN_BALANCESHEET_START';
export const FORGETPIN_BALANCESHEET_SUCCESS = 'FORGETPIN_BALANCESHEET_SUCCESS';
export const FORGETPIN_BALANCESHEET_ERROR = 'FORGETPIN_BALANCESHEET_ERROR';


export const ASSIGN_TRAINER_ERROR = 'ASSIGN_TRAINER_ERROR';
export const ASSIGN_TRAINER_START = 'ASSIGN_TRAINER_START';
export const ASSIGN_TRAINER_SUCCESS = 'ASSIGN_TRAINER_SUCCESS';

export const WORKOUT_DETAIL_ERROR = 'WORKOUT_DETAIL_ERROR';
export const WORKOUT_DETAIL_START = 'WORKOUT_DETAIL_START';
export const WORKOUT_DETAIL_SUCCESS = 'WORKOUT_DETAIL_SUCCESS';

export const ACTIVE_PLAN_ERROR = 'ACTIVE_PLAN_ERROR';
export const ACTIVE_PLAN_START = 'ACTIVE_PLAN_START';
export const ACTIVE_PLAN_SUCCESS = 'ACTIVE_PLAN_SUCCESS';

export const BALANCESHEET_PIN_ERROR = 'BALANCESHEET_PIN_ERROR';
export const BALANCESHEET_PIN_START = 'BALANCESHEET_PIN_START';
export const BALANCESHEET_PIN_SUCCESS = 'BALANCESHEET_PIN_SUCCESS';

export const FETCH_EXCERCISE_LIST_ERROR = 'FETCH_EXCERCISE_LIST_ERROR';
export const FETCH_EXCERCISE_LIST_START = 'FETCH_EXCERCISE_LIST_START';
export const FETCH_EXCERCISE_LIST_SUCCESS = 'FETCH_EXCERCISE_LIST_SUCCESS';

export const FETCH_ALL_ATTENDANCE_ERROR = 'FETCH_ALL_ATTENDANCE_ERROR';
export const FETCH_ALL_ATTENDANCE_START = 'FETCH_ALL_ATTENDANCE_START';
export const FETCH_ALL_ATTENDANCE_SUCCESS = 'FETCH_ALL_ATTENDANCE_SUCCESS';

export const FETCH_WORKOUT_LIST_START = 'FETCH_WORKOUT_LIST_START';
export const FETCH_WORKOUT_LIST_ERROR = 'FETCH_WORKOUT_LIST_ERROR';
export const FETCH_WORKOUT_LIST_SUCCESS = 'FETCH_WORKOUT_LIST_SUCCESS';

export const PAYMENT_SETTING_START = 'PAYMENT_SETTING_START';
export const PAYMENT_SETTING_ERROR = 'PAYMENT_SETTING_ERROR';
export const PAYMENT_SETTING_SUCCESS = 'PAYMENT_SETTING_SUCCESS';

export const ADD_WORKOUT_START = 'ADD_WORKOUT_START';
export const ADD_WORKOUT_ERROR = 'ADD_WORKOUT_ERROR';
export const ADD_WORKOUT_SUCCESS = 'ADD_WORKOUT_SUCCESS';

export const FETCH_ALLCITY_START = 'FETCH_ALLCITY_START';
export const FETCH_ALLCITY_SUCCESS = 'FETCH_ALLCITY_SUCCESS';
export const FETCH_ALLCITY_ERROR = 'FETCH_ALLCITY_ERROR';

export const FETCH_ALLSTATES_START = 'FETCH_ALLSTATES_START';
export const FETCH_ALLSTATES_SUCCESS = 'FETCH_ALLSTATES_SUCCESS';
export const FETCH_ALLSTATES_ERROR = 'FETCH_ALLSTATES_ERROR';

export const FETCH_ALLCOUNTRY_START = 'FETCH_ALLCOUNTRY_START';
export const FETCH_ALLCOUNTRY_SUCCESS = 'FETCH_ALLCOUNTRY_SUCCESS';
export const FETCH_ALLCOUNTRY_ERROR = 'FETCH_ALLCOUNTRY_ERROR';

export const FETCH_MEMBERDETAIL_START = 'FETCH_MEMBERDETAIL_START';
export const FETCH_MEMBERDETAIL_SUCCESS = 'FETCH_MEMBERDETAIL_SUCCESS';
export const FETCH_MEMBERDETAIL_ERROR = 'FETCH_MEMBERDETAIL_ERROR';

export const ALL_BALANCE_START = 'ALL_BALANCE_START';
export const ALL_BALANCE_SUCCESS = 'ALL_BALANCE_SUCCESS';
export const ALL_BALANCE_ERROR = 'ALL_BALANCE_ERROR';

export const REFERRAL_WITHDRAWAL_START = 'REFERRAL_WITHDRAWAL_START';
export const REFERRAL_WITHDRAWAL_SUCCESS = 'REFERRAL_WITHDRAWAL_SUCCESS';
export const REFERRAL_WITHDRAWAL_ERROR = 'REFERRAL_WITHDRAWAL_ERROR';

export const GET_ALL_REFERRALS_START = 'GET_ALL_REFERRALS_START';
export const GET_ALL_REFERRALS_SUCCESS = 'GET_ALL_REFERRALS_SUCCESS';
export const GET_ALL_REFERRALS_ERROR = 'GET_ALL_REFERRALS_ERROR';

export const GET_DASHBOARD_DETAIL_START = 'GET_DASHBOARD_DETAIL_START';
export const GET_DASHBOARD_DETAIL_SUCCESS = 'GET_DASHBOARD_DETAIL_SUCCESS';
export const GET_DASHBOARD_DETAIL_ERROR = 'GET_DASHBOARD_DETAIL_ERROR';

export const OWNER_PAYTM_START = 'OWNER_PAYTM_START';
export const OWNER_PAYTM_SUCCESS = 'OWNER_PAYTM_SUCCESS';
export const OWNER_PAYTM_ERROR = 'OWNER_PAYTM_ERROR';

export const RESEND_OTP_START = 'RESEND_OTP_START';
export const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS';
export const RESEND_OTP_ERROR = 'RESEND_OTP_ERROR';

export const FETCH_GYMLIST_START = 'FETCH_GYMLIST_START';
export const FETCH_GYMLIST_SUCCESS = 'FETCH_GYMLIST_SUCCESS';
export const FETCH_GYMLIST_ERROR = 'FETCH_GYMLIST_ERROR';

export const FETCH_ADDGYM_START = 'FETCH_ADDGYM_START';
export const FETCH_ADDGYM_SUCCESS = 'FETCH_ADDGYM_SUCCESS';
export const FETCH_ADDGYM_ERROR = 'FETCH_ADDGYM_ERROR';

export const FETCH_EDITGYM_START = 'FETCH_EDITGYM_START';
export const FETCH_EDITGYM_SUCCESS = 'FETCH_EDITGYM_SUCCESS';
export const FETCH_EDITGYM_ERROR = 'FETCH_EDITGYM_ERROR';

export const UPLOADGALLERY_START = 'UPLOADGALLERY_START';
export const UPLOADGALLERY_SUCCESS = 'UPLOADGALLERY_SUCCESS';
export const UPLOADGALLERY_ERROR = 'UPLOADGALLERY_ERROR';

export const FETCH_UPLOADGALLERY_START = 'FETCH_UPLOADGALLERY_START';
export const FETCH_UPLOADGALLERY_SUCCESS = 'FETCH_UPLOADGALLERY_SUCCESS';
export const FETCH_UPLOADGALLERY_ERROR = 'FETCH_UPLOADGALLERY_ERROR';

export const DELETE_UPLOADGALLERY_START = 'DELETE_UPLOADGALLERY_START';
export const DELETE_UPLOADGALLERY_SUCCESS = 'DELETE_UPLOADGALLERY_SUCCESS';
export const DELETE_UPLOADGALLERY_ERROR = 'DELETE_UPLOADGALLERY_ERROR';

export const FETCH_GYMSERVICES_START = 'FETCH_GYMSERVICES_START';
export const FETCH_GYMSERVICES_SUCCESS = 'FETCH_GYMSERVICES_SUCCESS';
export const FETCH_GYMSERVICES_ERROR = 'FETCH_GYMSERVICES_ERROR';

export const FETCH_USERTYPECOUNT_START = 'FETCH_USERTYPECOUNT_START';
export const FETCH_USERTYPECOUNT_SUCCESS = 'FETCH_USERTYPECOUNT_SUCCESS';
export const FETCH_USERTYPECOUNT_ERROR = 'FETCH_USERTYPECOUNT_ERROR';

export const ADDOREDIT_SUBSCRIPTIONPLAN_START =
  'ADDOREDIT_SUBSCRIPTIONPLAN_START';
export const ADDOREDIT_SUBSCRIPTIONPLAN_SUCCESS =
  'ADDOREDIT_SUBSCRIPTIONPLAN_SUCCESS';
export const ADDOREDIT_SUBSCRIPTIONPLAN_ERROR =
  'ADDOREDIT_SUBSCRIPTIONPLAN_ERROR';

export const ADDOREDIT_MEMBER_START = 'ADDOREDIT_MEMBER_START';
export const ADDOREDIT_MEMBER_SUCCESS = 'ADDOREDIT_MEMBER_SUCCESS';
export const ADDOREDIT_MEMBER_ERROR = 'ADDOREDIT_MEMBER_ERROR';

export const FETCH_GYMFACILITY_START = 'FETCH_GYMFACILITY_START';
export const FETCH_GYMFACILITY_SUCCESS = 'FETCH_GYMFACILITY_SUCCESS';
export const FETCH_GYMFACILITY_ERROR = 'FETCH_GYMFACILITY_ERROR';

export const FETCH_MEMBERS_START = 'FETCH_MEMBERS_START';
export const FETCH_MEMBERS_SUCCESS = 'FETCH_MEMBERS_SUCCESS';
export const FETCH_MEMBERS_ERROR = 'FETCH_MEMBERS_ERROR';

export const ADDOREDIT_MEMBERSTAFF_START = 'ADDOREDIT_MEMBERSTAFF_START';
export const ADDOREDIT_MEMBERSTAFF_SUCCESS = 'ADDOREDIT_MEMBERSTAFF_SUCCESS';
export const ADDOREDIT_MEMBERSTAFF_ERROR = 'ADDOREDIT_MEMBERSTAFF_ERROR';

export const GET_MEMBERSHIP_PLANS_START = 'GET_MEMBERSHIP_PLANS_START';
export const GET_MEMBERSHIP_PLANS_SUCCESS = 'GET_MEMBERSHIP_PLANS_SUCCESS';
export const GET_MEMBERSHIP_PLANS_ERROR = 'GET_MEMBERSHIP_PLANSF_ERROR';

export const RECIEVEPAYMENT_START = 'RECIEVEPAYMENT_START';
export const RECIEVEPAYMENT_SUCCESS = 'RECIEVEPAYMENT_SUCCESS';
export const RECIEVEPAYMENT_ERROR = 'RECIEVEPAYMENT_ERROR';


export const DELETE_MEMBERSHIP_START = 'DELETE_MEMBERSHIP_START';
export const DELETE_MEMBERSHIP_SUCCESS = 'DELETE_MEMBERSHIP_SUCCESS';
export const DELETE_MEMBERSHIP_ERROR = 'DELETE_MEMBERSHIP_ERROR';
// ----------------------------------

export const ADD_PLANS_START = 'ADD_PLANS_START';
export const ADD_PLANS_SUCCESS = 'ADD_PLANS_SUCCESS';
export const ADD_PLANS_ERROR = 'ADD_PLANS_ERROR';

export const SEARCH_GYM_START = 'SEARCH_GYM_START';
export const SEARCH_GYM_SUCCESS = 'SEARCH_GYM_SUCCESS';
export const SEARCH_GYM_ERROR = 'SEARCH_GYM_ERROR';

export const URL_ADD_GYM_START = 'URL_ADD_GYM_START';
export const URL_ADD_GYM_SUCCESS = 'URL_ADD_GYM_SUCCESS';
export const URL_ADD_GYM_ERROR = 'URL_ADD_GYM_ERROR';

export const BODY_PART_LIST_START = 'BODY_PART_LIST_START';
export const BODY_PART_LIST_SUCCESS = 'BODY_PART_LIST_SUCCESS';
export const BODY_PART_LIST_ERROR = 'BODY_PART_LIST_ERROR';

export const DELETE_MEMBER_START = 'DELETE_MEMBER_START';
export const DELETE_MEMBER_SUCCESS = 'DELETE_MEMBER_SUCCESS';
export const DELETE_MEMBER_ERROR = 'DELETE_MEMBER_ERROR';

export const DELETE_WORKOUT_START = 'DELETEWORKOUT_START';
export const DELETE_WORKOUT_SUCCESS = 'DELETEWORKOUT_SUCCESS';
export const DELETE_WORKOUT_ERROR = 'DELETEWORKOUT_ERROR';

export const ASSIGN_AS_TRAINER_START = ' ASSIGN_AS_TRAINER_START';
export const ASSIGN_AS_TRAINERR_SUCCESS = ' ASSIGN_AS_TRAINER_SUCCESS';
export const ASSIGN_AS_TRAINER_ERROR = ' ASSIGN_AS_TRAINER_ERROR';

export const ASSIGN_TO_MEMBER_START = ' ASSIGN_TO_MEMBER_START';
export const ASSIGN_TO_MEMBER_SUCCESS = ' ASSIGN_TO_MEMBER_SUCCESS';
export const ASSIGN_TO_MEMBER_ERROR = ' ASSIGN_TO_MEMBER_ERROR';
